name: Release the gem

on:
  create:
    ref_type: tag

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository == 'voxpupuli/beaker'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Build gem
        uses: scarhand/actions-ruby@master
        with:
          args: build *.gemspec
      - name: Publish gem
        uses: scarhand/actions-ruby@master
        env:
          RUBYGEMS_AUTH_TOKEN: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}
        with:
          args: push *.gem
